### ISSUE TITLE
Error detected while processing function

### ISSUE THREAD

**Issue by mikaelz** [lvht/phpcd.vim#85]
I'm getting `Error detected while processing function phpcd#CompletePHP[54]..phpcd#GetCurrentNameSpace[1]..rpc#request:`
Used vimrc https://pastebin.com/raw/6HqdKSLT

Some PHP errors pop up in the log (on the right) in the screencast https://www.youtube.com/watch?v=4XpOGjd5U2E

Please could you provide some help, don't know where to look for solution. Thanks.

**Comment by lvht** [comment]
please offer the content of `~/.phpcd.log`

**Comment by mikaelz** [comment]
Sorry, but doesn't have one `ls: cannot access '/home/mike/.phpcd.log': No such file or directory`

**Comment by lvht** [comment]
It seems like that you phpcd does not start. Debug this problem is a little hard.

First, go to https://github.com/lvht/phpcd.vim/blob/master/ftplugin/php_phpcd.vim#L4, and add line 
```viml
echomsg g:phpcd_php_cli_executable.' '.phpcd_path.' '.g:phpcd_root.' '.messenger.' '.g:php_autoload_path
```

Then, you can start vim and edit a php file. Vim will output something like,
```
php /home/lvht/Code/vim/phpcd.vim/php/main.php /home/lvht/Code/php/udplog msgpack /home/lvht/Code/php/udplog/vendor/autoload.php
```

You need run the output in your console. But before you run it, you need drop [this lines](https://github.com/lvht/phpcd.vim/blob/master/php/main.php#L1-L5) to let phpcd output error message.

**Comment by mikaelz** [comment]
Thanks, got the PHP error message I needed to resolve
`PHP Warning:  require(): open_basedir restriction in effect. File(/data/mike/Dropbox/dotfiles/.vim/bundle/phpcd.vim/php/../vendor/autoload.php) is not within the allowed path`

**Comment by lvht** [comment]
@mikaelz just comment the `open_basedir` will work.

**Comment by mikaelz** [comment]
Yeah that was my solution :)

**Comment by lvht** [comment]
I make a little change at 283924a04f1c99009188c24e91ce42420f0122a9. Now, all error will be output to `~/.phpcd.log`.
