### ISSUE TITLE
It does not work in case of warnings

### ISSUE THREAD

**Issue by DsTr** [lvht/phpcd.vim#97]
I'm using php from homebrew on OS X and it seem that php tries to load module several times (I found only one load of that module in /usr/local/etc/php/7.1/conf.d/ext-pcntl.ini after I removed that file error is gone and module still exist, but it seems this error comes by default after installation by brew)

PHP Warning:  Module 'pcntl' already loaded in Unknown on line 0

if this case vim just throws error for invalid argument for json_decode. 

for debug I tried to add
        if a:response =~ "WARNING:"
                return
        endif
        if a:response =~ "Warning:"
                return
        endif
to the beggining of s:OnCall and it works, but really not sure that it's possible to validate it, especially msgpack (neovim version did not work for me too)

**Comment by lvht** [comment]
phpcd.vim read from stdout of PHPCD.php process and parse the result as json/msgpack. If you php output some warning message, phpcd.vim will be confused. So the PHPCD.php should only output json/msgpack stream.

**Comment by DsTr** [comment]
Yes, I got this, I just was saying that it may be difficult to debug and maybe you can validate it somehow? At least to tell user that something is wrong with output?

**Comment by lvht** [comment]
For NeoVim, phpcd use the builtin msgpack-rpc api. NeoVim will read from phpcd's output and unpack according msgpack. If it read invalid msgpack stream (containing the error output), an error will be trigged. There no change to check these error.

For Vim, phpcd use the job channel and json api to emulate rpc call. We can do some check before call the json_decode function. But these approach is vim only.

But how to debug this problem? We need do the following,
1. Run a normal php file to ensure that no error/warning message has been output.
 This step is essential, because we can prevent php output error message during bootstrap.
2. set the `display_errors` to `stderr` by `ini_set('display_errors', 'stderr')`, so any further will be output to the **stderr**, and vim/nvim will display these error.
